package agendamentonutri;

import consulta.ListaConsulta;
import consulta.Consulta;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.table.DefaultTableModel;


public class TelaInicial extends javax.swing.JFrame {
    CadastroConsulta cadastro = new CadastroConsulta();
    DetalheConsulta finalizaConsul = new DetalheConsulta();
    
    
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCadastroConsulta = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        JScrollPane = new javax.swing.JScrollPane();
        tblAgendamento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Boas vindas ao sistema de Agendamento");

        btnCadastroConsulta.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCadastroConsulta.setText("Nova Consulta");
        btnCadastroConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroConsultaActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnExcluir.setText("Excluir Consulta");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnFinalizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnFinalizar.setText("Finalizar Consulta");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        tblAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paciênte", "CPF", "Telefone", "Data", "Já é paciênte?", "Consulta Realizada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JScrollPane.setViewportView(tblAgendamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnCadastroConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addGap(145, 145, 145)
                .addComponent(btnFinalizar)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroConsulta)
                    .addComponent(btnExcluir)
                    .addComponent(btnFinalizar))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroConsultaActionPerformed
        cadastro.MostraTela(this);
    }//GEN-LAST:event_btnCadastroConsultaActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        finalizaConsul.MostraTela(this);
    
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluirConsulta(pegaPosicao());
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton btnCadastroConsulta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable tblAgendamento;
    // End of variables declaration//GEN-END:variables
    
    
    
    private final String[] colunas = {"Paciênte", "CPF", "Telefone", "Data", "Já é paciênte?", "Consulta Realizada"};
    
    DefaultTableModel tabelaModelo = new DefaultTableModel(colunas, 0);
    
    private List<Consulta> listaConsulta = ListaConsulta.Listar();
    
    
    private void atualizar(){
        
        if(!listaConsulta.isEmpty()){
            
            Consulta consulta;
            
            tabelaModelo = new DefaultTableModel(colunas, 0);
            
            for(int i = 0; i < listaConsulta.size(); i++){
                
                consulta = listaConsulta.get(i);
                
                String[] linha = {consulta.getPaciente(), consulta.getCpf(), consulta.getTelefone(), 
                    consulta.getData(), consulta.getJaPaciente(), consulta.getStatus()};
                
                tabelaModelo.addRow(linha);
                
            }
        
            tblAgendamento.setModel(tabelaModelo);
        }
        else{
            tabelaModelo = new DefaultTableModel(colunas, 0);
            tblAgendamento.setModel(tabelaModelo);
        }
        
    }
    
    public void executaMetodo(){
        atualizar();
    
    }
    
    public int pegaPosicao(){
        
        int posicao = tblAgendamento.getSelectedRow();
        
        if(posicao == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione uma consulta!");
        
        }
        
        return posicao;
    }
    
    public void excluirConsulta(int pose){
        
        if(pose >= 0){
        
            String[] opcao = {"Sim", "Não"};
            
            int deletar = JOptionPane.showOptionDialog(rootPane, "Tem certeza que deseja excluir?", "Exclusão de Consulta", 
                    JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcao, opcao[0]);
            
            if(deletar == 0){
                
                ListaConsulta.Listar().remove(pose);
                atualizar();
            
            }
            else{
                tblAgendamento.clearSelection();
            }
            
        }
        
    }
    
    public Consulta seleciona(int pose){
       return ListaConsulta.Listar().get(pose);
    }

}
